// Sample data to demonstrate the platform
// In production, this would come from the database

export const sampleHousingListings = [
  {
    id: 'listing:sample-1',
    type: 'housing' as const,
    title: '1BR Apartment at Park Point - Spring Sublease',
    description: 'Fully furnished 1 bedroom apartment available for spring semester sublease. Close to campus with shuttle service. Includes all utilities, WiFi, and access to pool/gym. Perfect for co-op students!',
    price: 750,
    location: 'Park Point',
    bedrooms: 1,
    bathrooms: 1,
    availableFrom: '2026-01-15',
    availableTo: '2026-05-15',
    gender: 'any' as const,
    userId: 'sample-user-1',
    createdAt: '2026-02-01T10:00:00Z',
    status: 'available',
    housingType: 'Apartment',
    distanceFromCampus: 1.2,
    moveInDate: '2026-01-15',
    moveOutDate: '2026-05-15',
    roommateGender: 'any',
  },
  {
    id: 'listing:sample-2',
    type: 'housing' as const,
    title: 'Room in 3BR Townhouse - Female Preferred',
    description: 'Looking for a female roommate to fill a room in our 3BR townhouse. Walking distance to RIT. Shared kitchen and living room. Great housemates, quiet and clean environment.',
    price: 550,
    location: 'Perkins Green',
    bedrooms: 1,
    bathrooms: 1.5,
    availableFrom: '2026-03-01',
    availableTo: '2026-08-31',
    gender: 'female' as const,
    userId: 'sample-user-2',
    createdAt: '2026-02-03T14:30:00Z',
    status: 'available',
    housingType: 'House',
    distanceFromCampus: 0.8,
    moveInDate: '2026-03-01',
    moveOutDate: '2026-08-31',
    roommateGender: 'female',
  },
  {
    id: 'listing:sample-3',
    type: 'housing' as const,
    title: 'Studio Apartment - Province',
    description: 'Cozy studio apartment perfect for one person. Includes kitchen, bathroom, and living space. Quiet building with on-site laundry. Available for summer sublease.',
    price: 650,
    location: 'Province',
    bedrooms: 0,
    bathrooms: 1,
    availableFrom: '2026-05-15',
    availableTo: '2026-08-15',
    gender: 'any' as const,
    userId: 'sample-user-3',
    createdAt: '2026-02-04T09:15:00Z',
    status: 'available',
    housingType: 'Studio',
    distanceFromCampus: 2.1,
    moveInDate: '2026-05-15',
    moveOutDate: '2026-08-15',
    roommateGender: 'any',
  },
  {
    id: 'listing:sample-4',
    type: 'housing' as const,
    title: '2BR at The Hill - Co-op Ready',
    description: 'Spacious 2 bedroom apartment available now. Perfect for co-op students. Includes parking, utilities negotiable. Pet-friendly building with great amenities.',
    price: 900,
    location: 'The Hill',
    bedrooms: 2,
    bathrooms: 2,
    availableFrom: '2026-02-15',
    availableTo: '2026-12-31',
    gender: 'any' as const,
    userId: 'sample-user-4',
    createdAt: '2026-02-05T16:45:00Z',
    status: 'available',
    housingType: 'Apartment',
    distanceFromCampus: 1.5,
    moveInDate: '2026-02-15',
    moveOutDate: '2026-12-31',
    roommateGender: 'any',
  },
];

export const sampleMarketplaceListings = [
  {
    id: 'listing:sample-5',
    type: 'marketplace' as const,
    title: 'MacBook Pro 2021 - 13 inch',
    description: 'Selling my MacBook Pro in excellent condition. M1 chip, 8GB RAM, 256GB SSD. Includes original box and charger. Perfect for CS students!',
    price: 850,
    category: 'electronics',
    condition: 'like-new',
    userId: 'sample-user-5',
    createdAt: '2026-02-02T11:20:00Z',
    status: 'available',
  },
  {
    id: 'listing:sample-6',
    type: 'marketplace' as const,
    title: 'Calculus Textbook - 9th Edition',
    description: 'Barely used calculus textbook for MATH-181. All pages intact, no highlighting. Saved me from buying new at the bookstore!',
    price: 45,
    category: 'textbooks',
    condition: 'good',
    userId: 'sample-user-6',
    createdAt: '2026-02-01T08:30:00Z',
    status: 'available',
  },
  {
    id: 'listing:sample-7',
    type: 'marketplace' as const,
    title: 'IKEA Desk and Chair Set',
    description: 'Moving out and need to sell my desk setup. IKEA desk (48x24 inches) and ergonomic office chair. Good condition, some minor wear.',
    price: 75,
    category: 'furniture',
    condition: 'good',
    userId: 'sample-user-7',
    createdAt: '2026-02-03T13:00:00Z',
    status: 'available',
  },
  {
    id: 'listing:sample-8',
    type: 'marketplace' as const,
    title: 'Gaming Mouse - Logitech G502',
    description: 'Excellent gaming mouse with customizable weights and RGB lighting. Works perfectly, upgraded to wireless version.',
    price: 35,
    category: 'electronics',
    condition: 'good',
    userId: 'sample-user-8',
    createdAt: '2026-02-04T15:30:00Z',
    status: 'available',
  },
  {
    id: 'listing:sample-9',
    type: 'marketplace' as const,
    title: 'Winter Coat - North Face (Size M)',
    description: 'Black North Face winter coat, size medium. Perfect for Rochester winters! Only worn for one season, like new condition.',
    price: 120,
    category: 'clothing',
    condition: 'like-new',
    userId: 'sample-user-9',
    createdAt: '2026-02-05T10:00:00Z',
    status: 'available',
  },
  {
    id: 'listing:sample-10',
    type: 'marketplace' as const,
    title: 'Mini Fridge - Perfect for Dorms',
    description: 'Compact mini fridge, great for dorm rooms. Clean, works perfectly. Holds drinks and snacks. Energy efficient.',
    price: 60,
    category: 'furniture',
    condition: 'good',
    userId: 'sample-user-10',
    createdAt: '2026-02-05T17:00:00Z',
    status: 'available',
  },
];
